import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/Header'
import { cn } from '@/lib/utils'
import localFont from 'next/font/local'
import Footer from '@/components/Footer'

const univermagFont = localFont({
  src: [
    {
      path: '../../public/fonts/Univermag-Regular.otf',
      weight: '400',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Psychology Help',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'h-full w-full bg-main bg-cover bg-no-repeat text-[#342E24]',
          univermagFont.className
        )}
      >
        <Header />
        <div className="mx-auto flex flex-col items-center bg-[#A9A494] md:max-w-4xl lg:max-w-7xl">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
